include:
  - board: seeeduino_xiao
    shield: preonic_rak
    artifact-name: preonic_rak_xiao
  - board: seeeduino_xiao_ble
    shield: preonic_rak
    artifact-name: preonic_rak_xiao_ble
  - board: seeeduino_xiao_rp2040
    shield: preonic_rak
    artifact-name: preonic_rak_xiao_rp2040
  - board: seeeduino_xiao
    shield: preonic_rak
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: preonic_rak_xiao_studio
  - board: seeeduino_xiao_ble
    shield: preonic_rak
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: preonic_rak_xiao_ble_studio
  - board: seeeduino_xiao_rp2040
    shield: preonic_rak
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: preonic_rak_xiao_rp2040_studio
